source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '11.0'

def helpful
  pod 'SnapKit', '~> 5.0', :inhibit_warnings => true
  pod 'SwiftLint'
end

target 'WTestToolKit_Example' do
  helpful
  pod 'WTestToolKit', :path => '../'

  target 'WTestToolKit_Tests' do
    inherit! :search_paths
  end
end
